"""The contract between the research harness and a candidate solution.

A *solution* is one approach to fitting the Mandelbrot target (see groundtruth.py).
It can be anything that, given a training time budget, learns to map (real, imag) ->
target value: a neural net, a closed-form approximation, a spline/lookup scheme, etc.

IMMUTABLE: do not edit this file in the course of research. New approaches go in the
`solutions/` registry, each implementing `Solution`.

A solution module in `solutions/` must expose ONE of:
    - a module-level `SOLUTION` instance, or
    - a `build() -> Solution` factory.
See solutions/baseline_mlp.py for the canonical template.
"""

from __future__ import annotations

import time
from abc import ABC, abstractmethod

import torch

from harness import groundtruth as gt


class FitContext:
    """Everything a solution needs while training: device, time budget, and data.

    The harness constructs this and passes it to `Solution.fit`. Solutions decide
    their own sampling strategy (uniform, boundary-oversampled, adaptive, multi-res,
    curriculum, ...) — that choice is part of the algorithm being researched.
    """

    def __init__(self, device: torch.device, time_budget_s: float, seed: int = 0):
        self.device = device
        self.time_budget_s = float(time_budget_s)
        self._start = time.monotonic()
        self._deadline = self._start + self.time_budget_s
        self.generator = torch.Generator(device=device).manual_seed(seed)

    # --- time -----------------------------------------------------------------
    def elapsed(self) -> float:
        return time.monotonic() - self._start

    def time_left(self) -> float:
        """Seconds remaining until the *target* training budget is reached."""
        return max(0.0, self._deadline - time.monotonic())

    def expired(self) -> bool:
        """True once the target budget is exhausted. Solutions should stop training."""
        return time.monotonic() >= self._deadline

    # --- data -----------------------------------------------------------------
    def sample(self, n: int):
        """Return (coords[n,2], targets[n]) of uniform random points, on device."""
        coords = gt.sample_uniform(n, generator=self.generator, device=self.device)
        targets = gt.mandelbrot(coords)
        return coords, targets

    def ground_truth(self, coords: torch.Tensor) -> torch.Tensor:
        """Compute targets for arbitrary coords (use for custom sampling schemes)."""
        return gt.mandelbrot(coords.to(self.device))

    def log(self, msg: str) -> None:
        print(f"[fit t={self.elapsed():6.1f}s] {msg}", flush=True)


class Solution(ABC):
    """Base class every approach implements.

    Required: `name`, `description`, `fit`, `predict`.
    Provide `save`/`load` if you subclass directly; `TorchSolution` implements them.
    """

    name: str = "unnamed"
    description: str = ""

    @abstractmethod
    def fit(self, ctx: FitContext) -> None:
        """Train within the time budget. Use ctx.sample()/ctx.ground_truth() for data
        and ctx.expired()/ctx.time_left() to respect the budget."""

    @abstractmethod
    def predict(self, coords: torch.Tensor) -> torch.Tensor:
        """Map (N, 2) coords -> (N,) predicted target values. Inference only
        (the harness wraps calls in torch.no_grad). Values should lie in [0, 1]."""

    def save(self, path: str) -> None:
        raise NotImplementedError

    def load(self, path: str) -> None:
        raise NotImplementedError


class TorchSolution(Solution):
    """Convenience base for nn.Module-based solutions.

    Subclasses set `self.model` (an nn.Module mapping (N,2)->(N,) or (N,1)) and
    implement `fit`. `predict`, `save`, `load` are handled here.
    """

    model: torch.nn.Module = None
    device: torch.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    @torch.no_grad()
    def predict(self, coords: torch.Tensor) -> torch.Tensor:
        self.model.eval()
        coords = coords.to(self.device)
        out = self.model(coords)
        return out.reshape(-1).clamp(0.0, 1.0)

    def save(self, path: str) -> None:
        torch.save({"state_dict": self.model.state_dict(),
                    "name": self.name,
                    "description": self.description}, path)

    def load(self, path: str) -> None:
        ckpt = torch.load(path, map_location=self.device)
        self.model.load_state_dict(ckpt["state_dict"])
        self.model.to(self.device)
